# generated by fastapi-codegen:
#   filename:  network-slice-booking.yaml
#   timestamp: 2025-10-04T21:35:03+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum, StrEnum
from typing import List, Optional, TypeAlias
from uuid import UUID

from pydantic import BaseModel, Field, confloat, conint, constr
from typing import Annotated


class SessionId(BaseModel):
    session_id: Annotated[UUID, Field(description='Session ID in UUID format')]


class TimeUnitEnum(StrEnum):
    Days = 'Days'
    Hours = 'Hours'
    Minutes = 'Minutes'
    Seconds = 'Seconds'
    Milliseconds = 'Milliseconds'
    Microseconds = 'Microseconds'
    Nanoseconds = 'Nanoseconds'


class RateUnitEnum(StrEnum):
    bps = 'bps'
    kbps = 'kbps'
    Mbps = 'Mbps'
    Gbps = 'Gbps'
    Tbps = 'Tbps'


# Pydantic v2-friendly type aliases
NumberOfDevices = Annotated[
    int,
    Field(
        ...,
        description='Maximum number of devices that is allowed to be connected to the network at any point in time.'
    ),
]


class TimePeriod(BaseModel):
    startDate: Optional[datetime] = Field(
        ...,
        description='An instant of time, starting of the TimePeriod. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.',
        example='2024-06-01T12:00:00Z',
    )
    endDate: Optional[datetime] = Field(
        ...,
        description='An instant of time, ending of the TimePeriod. If not included, then the period has no ending date. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.',
        example='2024-06-02T12:00:00Z',
    )


class AreaType(Enum):
    CIRCLE = 'CIRCLE'
    POLYGON = 'POLYGON'


Latitude = Annotated[
    float,
    Field(ge=-90.0, le=90.0, description='Latitude component of a location'),
]


Longitude = Annotated[
    float,
    Field(ge=-180.0, le=180.0, description='Longitude component of location'),
]

class Duration(BaseModel):
    value: Optional[conint(ge=1)] = Field(
        ..., description='Length of duration', example=12
    )
    unit: Optional[TimeUnitEnum] = None


class Rate(BaseModel):
    value: Optional[conint(ge=0, le=1024)] = Field(
        ..., description='Quantity of rate', example=10
    )
    unit: Optional[RateUnitEnum] = None


class Area(BaseModel):
    areaType: Optional[AreaType] = Field(default=None)


class Point(BaseModel):
    latitude: Latitude
    longitude: Longitude


class SliceQosProfile(BaseModel):
    maxNumOfDevices: Optional[NumberOfDevices] = Field(
        ...,
        description='maxNumOfDevices is a maximum number of devices that can be connected to the slice\n',
    )
    downStreamRatePerDevice: Optional[Rate] = Field(
        ...,
        description='downStreamRatePerDevice is the maximum downstream rate allowed for each device connected to the slice.\nIt indicates the individual device capability required for the slice.\n',
    )
    upStreamRatePerDevice: Optional[Rate] = Field(
        ...,
        description='upStreamRatePerDevice is the maximum upstream rate allowed for each device connected to the slice.\nIt indicates the individual device capability required for the slice.\n',
    )
    downStreamDelayBudget: Optional[Duration] = Field(
        ...,
        description='downStreamDelayBudget is the maximum allowable downlink packet transmission latency (millisecond).\nBy limiting the delay, the network can provide an acceptable level of performance for various services, such as voice calls, video streaming, and data.\n',
    )
    upStreamDelayBudget: Optional[Duration] = Field(
        ...,
        description='upStreamDelayBudget is the maximum allowable uplink packet transmission latency (millisecond).\nBy limiting the delay, the network can provide an acceptable level of performance for various services, such as voice calls, video streaming, and data.\n',
    )


class Circle(Area):
    center: Point
    radius: confloat(ge=1.0) = Field(
        ..., description='Distance from the center in meters'
    )

PointList: TypeAlias = Annotated[
    List['Point'],
    Field(
        description='List of points defining a polygon',
        min_items=3,
        max_items=15,
    ),
]


class CreateSession(BaseModel):
    serviceTime: Optional[TimePeriod] = Field(
        ...,
        description='serviceTime is a period during which the network slice will be reserved.\nIt is defined by a start time and an end time.\n',
    )
    serviceArea: Optional[Area] = Field(
        ...,
        description='serviceArea is a geographical area where the network slice will be reserved.\nIt can be defined as a circle or a polygon.\n',
    )
    sliceQosProfile: Optional[SliceQosProfile] = Field(
        ...,
        description='sliceQosProfile is a set of quality of service parameters that define the requirements for the network slice.\nIt includes parameters such as maximum number of devices, downlink and uplink throughput per device, and latency requirements.\n',
    )


class Polygon(Area):
    boundary: PointList


class SessionInfo(CreateSession):
    sessionId: SessionId
